spring:
  mandatory-file-encoding: UTF-8
  profiles:
    active:
      - dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://dockermysql:3306/springboot?useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    hikari-maximum-pool-size: 1
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        order_by_default_null_ordering: last

server:
  port: 8082
debug: true